### ISSUE TITLE
[Bug]: Tuba crashes on sent messages

### ISSUE THREAD

**Issue by lcruggeri** [GeopJr/Tuba#261]
### Describe the bug

It doesn't happen everytime, but i get Tuba to crash sending a toot, with or without emoji or mention.

Will try to update logs but it didn't produce any

### Steps To Reproduce

1. Open the new message popup
2. Write a message with emoji or mention
3. Watch Tuba crash or not, seems random

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

Arch Linux

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.3.0 (production)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.1 (3.4.1)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by fabiscafe** [comment]
Hi. It's the same for me with the "native" Arch Linux build. Sometimes after the click on publish it will crash. I was unable to reliable recreate this. :(

This is mastodon @ mstdn.social

os: Arch Linux (null)
prefix: /usr
flatpak: false
version: 0.3.0 (production)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)

a backtrace is here:

```
Core was generated by `/usr/bin/dev.geopjr.Tuba'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (Thread 0x7f2044e945c0 (LWP 38000))]
(gdb) bt full
#0  0x0000000000000000 in  ()
#1  0x00005597d679adea in tuba_dialogs_compose_real_transaction_co.isra.0 (_data_=0x5597f0fb1940)
    at dev.geopjr.Tuba.p/src/Dialogs/Composer/Dialog.c:1254
#2  0x00007f20492793f4 in g_task_return_now (task=0x5597f0f60fc0) at ../glib/gio/gtask.c:1309
#3  0x00007f204927d08d in g_task_return (type=<optimized out>, task=0x5597f0f60fc0) at ../glib/gio/gtask.c:1378
        source = 0x5597eaf0d470
#4  g_task_return (task=0x5597f0f60fc0, type=<optimized out>) at ../glib/gio/gtask.c:1335
#5  0x00007f204927d784 in g_task_return_pointer (task=<optimized out>, result=<optimized out>, result_destroy=<optimized out>)
    at ../glib/gio/gtask.c:1812
        __func__ = "g_task_return_pointer"
#6  0x00005597d6795f3d in tuba_request_await_co.isra.0 (_data_=0x5597eaf52f20)
    at dev.geopjr.Tuba.p/src/Services/Network/Request.c:1408
#7  0x00005597d674f418 in __lambda5_ (obj=<optimized out>, res=<optimized out>, _data33_=0x5597e7066a50)
    at dev.geopjr.Tuba.p/src/Services/Network/Network.c:253
        _tmp4_ = <optimized out>
        _tmp1_ = 0x5597f0848920
        status = 200
        _tmp3_ = 200
        in_stream = 0x5597f0848920
        _tmp0_ = <optimized out>
        _tmp2_ = 200
        self = 0x5597d819e3b0
        _inner_error0_ = 0x0
#8  ___lambda5__gasync_ready_callback (source_object=<optimized out>, res=<optimized out>, self=0x5597e7066a50)
    at dev.geopjr.Tuba.p/src/Services/Network/Network.c:353
--Type <RET> for more, q to quit, c to continue without paging--c
#9  0x00007f20492793f4 in g_task_return_now (task=0x5597f0f5b650) at ../glib/gio/gtask.c:1309
#10 0x00007f204927d08d in g_task_return (type=<optimized out>, task=0x5597f0f5b650) at ../glib/gio/gtask.c:1378
        source = 0x5597eaf0d470
#11 g_task_return (task=0x5597f0f5b650, type=<optimized out>) at ../glib/gio/gtask.c:1335
#12 0x00007f204927d784 in g_task_return_pointer (task=<optimized out>, result=<optimized out>, result_destroy=<optimized out>)
    at ../glib/gio/gtask.c:1812
        __func__ = "g_task_return_pointer"
#13 0x00007f2049409533 in async_send_request_return_result (item=0x5597f0f5ab60, stream=0x5597f0848920, error=0x0)
    at ../libsoup/libsoup/soup-session.c:2675
        task = 0x5597f0f5b650
        __func__ = "async_send_request_return_result"
#14 0x00007f204940ce2d in send_async_maybe_complete (stream=0x5597f0848920, item=0x5597f0f5ab60) at ../libsoup/libsoup/soup-session.c:2789
        stream = 0x5597f0848920
        error = 0x0
#15 run_until_read_done (msg=0x5597dd41fce0, result=<optimized out>, item=0x5597f0f5ab60) at ../libsoup/libsoup/soup-session.c:2811
        stream = 0x5597f0848920
        error = 0x0
#16 0x00007f20492793f4 in g_task_return_now (task=0x5597f2f87770) at ../glib/gio/gtask.c:1309
#17 0x00007f204927d08d in g_task_return (type=<optimized out>, task=0x5597f2f87770) at ../glib/gio/gtask.c:1378
        source = 0x5597eaf0d470
#18 g_task_return (task=0x5597f2f87770, type=<optimized out>) at ../glib/gio/gtask.c:1335
#19 0x00007f204927d98e in g_task_return_boolean (task=<optimized out>, result=<optimized out>) at ../glib/gio/gtask.c:1924
        __func__ = "g_task_return_boolean"
#20 0x00007f20493dbed3 in soup_http2_message_data_check_status (data=0x5597f0802370)
    at ../libsoup/libsoup/http2/soup-client-message-io-http2.c:294
        io = 0x5597eaf14330
        msg = 0x5597dd41fce0
        task = 0x5597f2f87770
        error = 0x0
#21 0x00007f20495bc850 in g_list_foreach
    (list=<optimized out>, func=func@entry=0x7f20493dbd70 <soup_http2_message_data_check_status>, user_data=user_data@entry=0x0)
    at ../glib/glib/glist.c:1092
        next = 0x0
#22 0x00007f20493d9832 in io_read_ready (stream=<optimized out>, io=0x5597eaf14330)
    at ../libsoup/libsoup/http2/soup-client-message-io-http2.c:445
        error = 0x0
        progress = <optimized out>
        conn = 0x5597f0844720
#23 0x00007f20495c653b in g_main_dispatch (context=0x5597d8128b80) at ../glib/glib/gmain.c:3460
        dispatch = 0x7f2049258d50 <pollable_source_dispatch>
        prev_source = 0x0
        begin_time_nsec = 45277817080899
        was_in_call = 0
        user_data = 0x5597eaf14330
        callback = 0x7f20493d9780 <io_read_ready>
        cb_funcs = 0x7f20496b5380 <g_source_callback_funcs>
        cb_data = 0x5597f08497e0
        need_destroy = <optimized out>
        source = 0x5597eaf0d470
        current = 0x5597d8130e30
        i = 3
#24 g_main_context_dispatch (context=0x5597d8128b80) at ../glib/glib/gmain.c:4200
#25 0x00007f2049623219 in g_main_context_iterate.constprop.0 (context=0x5597d8128b80, block=1, dispatch=1, self=<optimized out>)
    at ../glib/glib/gmain.c:4276
        max_priority = 2147483647
        timeout = 16
        some_ready = 1
        nfds = 7
        allocated_nfds = <optimized out>
        fds = <optimized out>
        begin_time_nsec = 45277811330463
#26 0x00007f20495c51a2 in g_main_context_iteration (context=context@entry=0x5597d8128b80, may_block=may_block@entry=1)
    at ../glib/glib/gmain.c:4343
        retval = <optimized out>
#27 0x00007f20492ad3be in g_application_run (application=application@entry=0x5597d80f1410, argc=<optimized out>, argv=0x7ffd3d968088)
    at ../glib/gio/gapplication.c:2573
        arguments = 0x5597d8139820
        status = 0
        context = 0x5597d8128b80
        acquired_context = <optimized out>
        __func__ = "g_application_run"
#28 0x00005597d670f47a in tuba_application_main (args_length1=<optimized out>, args=<optimized out>)
    at dev.geopjr.Tuba.p/src/Application.c:728
        _tmp20_ = 0x5597d80f1410
        _tmp19_ = 0x5597d80f1410
        _inner_error0_ = 0x0
#29 main (argc=<optimized out>, argv=<optimized out>) at dev.geopjr.Tuba.p/src/Application.c:736
```

**Comment by bittin** [comment]
same for me on the updated PKGBUILD i built (but had not noticed it before @fabiscafe told me)

**Comment by GeopJr** [comment]
Sorry everyone and thanks for the report!

This only happened when replying to someone, right? If not, let me know!

**Comment by GeopJr** [comment]
I'll make a patch release as soon as someone confirms that its fixed, since this is an important one

**Comment by lcruggeri** [comment]
Tuba 0.3.1 flatpak, not crashes on reply with emoji and normal posting
